-- ============================================================================
-- GRAVVIA ENGAGE — COMPLETE SUPABASE SETUP (single file)
-- ----------------------------------------------------------------------------
-- Paste this entire file into the Supabase SQL Editor and run it once.
-- It is idempotent: safe to re-run (uses IF NOT EXISTS / ON CONFLICT DO NOTHING).
--
-- What it does:
--   1. Enables required extensions (uuid-ossp, pgcrypto)
--   2. Creates all 20 tables matching the backend types
--   3. Creates indexes + updated_at triggers
--   4. Enables Row Level Security (backend uses service_role which bypasses RLS)
--   5. Seeds roles + permissions (RBAC)
--   6. Seeds 3 sample clients + settings + contacts
--   7. Creates a WORKING super-admin login:
--        email:    admin@gravvia.com
--        password: Admin1234!
--      (hash is generated by pgcrypto bcrypt — verifiable by bcryptjs in the API)
--
-- >>> CHANGE THE ADMIN PASSWORD below before using in production. <<<
-- ============================================================================

-- ─────────────────────────────────────────────
-- 1. EXTENSIONS
-- ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────
-- 2. TABLES
-- ─────────────────────────────────────────────

-- CLIENTS
CREATE TABLE IF NOT EXISTS clients (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name            TEXT NOT NULL,
  slug            TEXT NOT NULL UNIQUE,
  industry        TEXT NOT NULL DEFAULT 'other',
  timezone        TEXT NOT NULL DEFAULT 'America/New_York',
  phone_numbers   TEXT[] NOT NULL DEFAULT '{}',
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','suspended')),
  retell_agent_id TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_clients_slug ON clients(slug);
CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status);

-- CLIENT SETTINGS
CREATE TABLE IF NOT EXISTS client_settings (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id             UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  agent_prompt          TEXT NOT NULL DEFAULT '',
  agent_personality     TEXT NOT NULL DEFAULT 'professional',
  agent_tone            TEXT NOT NULL DEFAULT 'friendly',
  agent_response_style  TEXT NOT NULL DEFAULT 'concise',
  faqs                  JSONB NOT NULL DEFAULT '[]',
  services              JSONB NOT NULL DEFAULT '[]',
  pricing               JSONB NOT NULL DEFAULT '[]',
  business_policies     TEXT[] NOT NULL DEFAULT '{}',
  booking_enabled       BOOLEAN NOT NULL DEFAULT false,
  booking_rules         JSONB NOT NULL DEFAULT '{}',
  notification_emails   TEXT[] NOT NULL DEFAULT '{}',
  escalation_rules      JSONB NOT NULL DEFAULT '[]',
  crm_type              TEXT NOT NULL DEFAULT 'none',
  crm_config            JSONB NOT NULL DEFAULT '{}',
  custom_field_mapping  JSONB NOT NULL DEFAULT '{}',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(client_id)
);

-- USERS
CREATE TABLE IF NOT EXISTS users (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email         TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('super_admin','admin','agent','viewer')),
  client_id     UUID REFERENCES clients(id) ON DELETE SET NULL,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  last_login_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_client_id ON users(client_id);

-- ROLES & PERMISSIONS (RBAC lookup)
CREATE TABLE IF NOT EXISTS roles (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name        TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS permissions (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  role_id     UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission  TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(role_id, permission)
);

-- API KEYS
CREATE TABLE IF NOT EXISTS api_keys (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id    UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  key_hash     TEXT NOT NULL UNIQUE,
  permissions  TEXT[] NOT NULL DEFAULT '{}',
  last_used_at TIMESTAMPTZ,
  expires_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys(key_hash);
CREATE INDEX IF NOT EXISTS idx_api_keys_client ON api_keys(client_id);

-- CONTACTS
CREATE TABLE IF NOT EXISTS contacts (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id        UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  external_crm_id  TEXT,
  first_name       TEXT NOT NULL DEFAULT '',
  last_name        TEXT NOT NULL DEFAULT '',
  email            TEXT,
  phone            TEXT NOT NULL,
  notes            TEXT,
  tags             TEXT[] NOT NULL DEFAULT '{}',
  custom_fields    JSONB NOT NULL DEFAULT '{}',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contacts_client ON contacts(client_id);
CREATE INDEX IF NOT EXISTS idx_contacts_phone ON contacts(phone);
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_crm ON contacts(external_crm_id);

-- CALLS
CREATE TABLE IF NOT EXISTS calls (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id        UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  contact_id       UUID REFERENCES contacts(id) ON DELETE SET NULL,
  retell_call_id   TEXT NOT NULL UNIQUE,
  direction        TEXT NOT NULL DEFAULT 'inbound' CHECK (direction IN ('inbound','outbound')),
  from_number      TEXT NOT NULL,
  to_number        TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress','completed','failed','transferred')),
  duration_seconds INTEGER,
  recording_url    TEXT,
  started_at       TIMESTAMPTZ NOT NULL,
  ended_at         TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_calls_client ON calls(client_id);
CREATE INDEX IF NOT EXISTS idx_calls_contact ON calls(contact_id);
CREATE INDEX IF NOT EXISTS idx_calls_retell ON calls(retell_call_id);
CREATE INDEX IF NOT EXISTS idx_calls_status ON calls(status);
CREATE INDEX IF NOT EXISTS idx_calls_started ON calls(started_at DESC);

-- CONVERSATIONS
CREATE TABLE IF NOT EXISTS conversations (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  call_id           UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  client_id         UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  contact_id        UUID REFERENCES contacts(id) ON DELETE SET NULL,
  intent            TEXT,
  sentiment         TEXT,
  lead_captured     BOOLEAN NOT NULL DEFAULT false,
  booking_requested BOOLEAN NOT NULL DEFAULT false,
  handoff_requested BOOLEAN NOT NULL DEFAULT false,
  summary           TEXT,
  metadata          JSONB NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(call_id)
);
CREATE INDEX IF NOT EXISTS idx_conversations_call ON conversations(call_id);
CREATE INDEX IF NOT EXISTS idx_conversations_client ON conversations(client_id);

-- CALL TRANSCRIPTS
CREATE TABLE IF NOT EXISTS call_transcripts (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  call_id    UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  client_id  UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  transcript JSONB NOT NULL DEFAULT '[]',
  word_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(call_id)
);
CREATE INDEX IF NOT EXISTS idx_transcripts_call ON call_transcripts(call_id);
CREATE INDEX IF NOT EXISTS idx_transcripts_client ON call_transcripts(client_id);

-- CALL SUMMARIES
CREATE TABLE IF NOT EXISTS call_summaries (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  call_id             UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  client_id           UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  summary             TEXT NOT NULL,
  action_items        TEXT[] NOT NULL DEFAULT '{}',
  key_topics          TEXT[] NOT NULL DEFAULT '{}',
  sentiment           TEXT NOT NULL DEFAULT 'neutral' CHECK (sentiment IN ('positive','neutral','negative')),
  follow_up_required  BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(call_id)
);
CREATE INDEX IF NOT EXISTS idx_summaries_call ON call_summaries(call_id);
CREATE INDEX IF NOT EXISTS idx_summaries_client ON call_summaries(client_id);

-- APPOINTMENTS
CREATE TABLE IF NOT EXISTS appointments (
  id                   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id            UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  contact_id           UUID NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  call_id              UUID REFERENCES calls(id) ON DELETE SET NULL,
  external_calendar_id TEXT,
  title                TEXT NOT NULL,
  description          TEXT,
  start_time           TIMESTAMPTZ NOT NULL,
  end_time             TIMESTAMPTZ NOT NULL,
  timezone             TEXT NOT NULL,
  status               TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','cancelled','rescheduled','completed','no_show')),
  service_type         TEXT,
  staff_member_id      UUID,
  notes                TEXT,
  reminder_sent        BOOLEAN NOT NULL DEFAULT false,
  metadata             JSONB NOT NULL DEFAULT '{}',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_appointments_client ON appointments(client_id);
CREATE INDEX IF NOT EXISTS idx_appointments_contact ON appointments(contact_id);
CREATE INDEX IF NOT EXISTS idx_appointments_start ON appointments(start_time);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments(status);

-- CRM CONNECTIONS
CREATE TABLE IF NOT EXISTS crm_connections (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id             UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  crm_type              TEXT NOT NULL,
  credentials_encrypted TEXT NOT NULL,
  pipeline_id           TEXT,
  stage_mapping         JSONB NOT NULL DEFAULT '{}',
  custom_field_mapping  JSONB NOT NULL DEFAULT '{}',
  crm_config            JSONB NOT NULL DEFAULT '{}',
  is_active             BOOLEAN NOT NULL DEFAULT true,
  last_sync_at          TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(client_id, crm_type)
);
CREATE INDEX IF NOT EXISTS idx_crm_connections_client ON crm_connections(client_id);

-- CRM SYNC LOGS
CREATE TABLE IF NOT EXISTS crm_sync_logs (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id           UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  crm_connection_id   UUID NOT NULL REFERENCES crm_connections(id) ON DELETE CASCADE,
  entity_type         TEXT NOT NULL,
  entity_id           UUID NOT NULL,
  operation           TEXT NOT NULL CHECK (operation IN ('create','update','delete')),
  status              TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('success','failed','pending')),
  external_id         TEXT,
  error_message       TEXT,
  attempts            INTEGER NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_crm_sync_logs_client ON crm_sync_logs(client_id);
CREATE INDEX IF NOT EXISTS idx_crm_sync_logs_status ON crm_sync_logs(status);
CREATE INDEX IF NOT EXISTS idx_crm_sync_logs_entity ON crm_sync_logs(entity_type, entity_id);

-- EVENTS
CREATE TABLE IF NOT EXISTS events (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id        UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  event_type       TEXT NOT NULL,
  source           TEXT NOT NULL,
  payload          JSONB NOT NULL DEFAULT '{}',
  processed        BOOLEAN NOT NULL DEFAULT false,
  idempotency_key  TEXT NOT NULL UNIQUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_events_client ON events(client_id);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_processed ON events(processed);
CREATE INDEX IF NOT EXISTS idx_events_idempotency ON events(idempotency_key);

-- AUTOMATION RULES
CREATE TABLE IF NOT EXISTS automation_rules (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id  UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  trigger    TEXT NOT NULL,
  conditions JSONB NOT NULL DEFAULT '[]',
  actions    JSONB NOT NULL DEFAULT '[]',
  is_active  BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_automation_rules_client ON automation_rules(client_id);
CREATE INDEX IF NOT EXISTS idx_automation_rules_trigger ON automation_rules(trigger);

-- AUTOMATION RUNS
CREATE TABLE IF NOT EXISTS automation_runs (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  rule_id          UUID NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE,
  client_id        UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  trigger_event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  status           TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running','completed','failed')),
  result           JSONB,
  error_message    TEXT,
  started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at     TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_automation_runs_rule ON automation_runs(rule_id);
CREATE INDEX IF NOT EXISTS idx_automation_runs_client ON automation_runs(client_id);

-- FAILED JOBS
CREATE TABLE IF NOT EXISTS failed_jobs (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  queue_name    TEXT NOT NULL,
  job_id        TEXT NOT NULL,
  job_data      JSONB NOT NULL DEFAULT '{}',
  error_message TEXT NOT NULL,
  attempts      INTEGER NOT NULL DEFAULT 0,
  status        TEXT NOT NULL DEFAULT 'failed' CHECK (status IN ('failed','manual_review','resolved')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_failed_jobs_status ON failed_jobs(status);
CREATE INDEX IF NOT EXISTS idx_failed_jobs_queue ON failed_jobs(queue_name);

-- STAFF NOTIFICATIONS
CREATE TABLE IF NOT EXISTS staff_notifications (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id        UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  call_id          UUID REFERENCES calls(id) ON DELETE SET NULL,
  type             TEXT NOT NULL CHECK (type IN ('handoff','lead','booking','escalation')),
  status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','connected','missed','resolved')),
  message          TEXT NOT NULL,
  recipient_email  TEXT,
  metadata         JSONB NOT NULL DEFAULT '{}',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_staff_notifications_client ON staff_notifications(client_id);
CREATE INDEX IF NOT EXISTS idx_staff_notifications_status ON staff_notifications(status);

-- AUDIT LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
  client_id   UUID REFERENCES clients(id) ON DELETE CASCADE,
  action      TEXT NOT NULL,
  entity_type TEXT,
  entity_id   UUID,
  old_value   JSONB,
  new_value   JSONB,
  ip_address  INET,
  user_agent  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_client ON audit_logs(client_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at DESC);

-- ─────────────────────────────────────────────
-- 3. updated_at TRIGGERS
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_clients_updated_at ON clients;
CREATE TRIGGER trg_clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_client_settings_updated_at ON client_settings;
CREATE TRIGGER trg_client_settings_updated_at BEFORE UPDATE ON client_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_contacts_updated_at ON contacts;
CREATE TRIGGER trg_contacts_updated_at BEFORE UPDATE ON contacts FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_calls_updated_at ON calls;
CREATE TRIGGER trg_calls_updated_at BEFORE UPDATE ON calls FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_conversations_updated_at ON conversations;
CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_appointments_updated_at ON appointments;
CREATE TRIGGER trg_appointments_updated_at BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_crm_connections_updated_at ON crm_connections;
CREATE TRIGGER trg_crm_connections_updated_at BEFORE UPDATE ON crm_connections FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_crm_sync_logs_updated_at ON crm_sync_logs;
CREATE TRIGGER trg_crm_sync_logs_updated_at BEFORE UPDATE ON crm_sync_logs FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_automation_rules_updated_at ON automation_rules;
CREATE TRIGGER trg_automation_rules_updated_at BEFORE UPDATE ON automation_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_failed_jobs_updated_at ON failed_jobs;
CREATE TRIGGER trg_failed_jobs_updated_at BEFORE UPDATE ON failed_jobs FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ─────────────────────────────────────────────
-- 4. ROW LEVEL SECURITY
-- The backend connects with the service_role key, which bypasses RLS.
-- Enabling RLS with no permissive policies blocks anon/authenticated direct
-- access — all access must flow through the backend. This is intentional.
-- ─────────────────────────────────────────────
ALTER TABLE clients              ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_settings      ENABLE ROW LEVEL SECURITY;
ALTER TABLE users                ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles                ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys             ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts             ENABLE ROW LEVEL SECURITY;
ALTER TABLE calls                ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations        ENABLE ROW LEVEL SECURITY;
ALTER TABLE call_transcripts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE call_summaries       ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments         ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_connections      ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_sync_logs        ENABLE ROW LEVEL SECURITY;
ALTER TABLE events               ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_rules     ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_runs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE failed_jobs          ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_notifications  ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs           ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────
-- 4b. MULTI-TENANT HARDENING CONSTRAINTS
-- Relied upon by the application code.
-- ─────────────────────────────────────────────

-- CRM sync logs: retries UPDATE one row instead of inserting duplicates.
-- The crm-sync worker upserts on (client_id, entity_type, entity_id, operation).
ALTER TABLE crm_sync_logs DROP CONSTRAINT IF EXISTS uq_crm_sync_entity;
ALTER TABLE crm_sync_logs
  ADD CONSTRAINT uq_crm_sync_entity
  UNIQUE (client_id, entity_type, entity_id, operation);

-- A Retell agent id maps to exactly one client (unambiguous webhook routing).
CREATE UNIQUE INDEX IF NOT EXISTS uq_clients_retell_agent
  ON clients(retell_agent_id) WHERE retell_agent_id IS NOT NULL;

-- OPTIONAL per-client Retell webhook secret (only if clients use separate
-- Retell accounts; leave NULL when sharing one workspace).
ALTER TABLE clients ADD COLUMN IF NOT EXISTS retell_webhook_secret TEXT;

-- ─────────────────────────────────────────────
-- 5. SEED: ROLES + PERMISSIONS
-- ─────────────────────────────────────────────
INSERT INTO roles (name, description) VALUES
  ('super_admin', 'Full platform access'),
  ('admin', 'Client admin with full client access'),
  ('agent', 'Operational agent with limited write access'),
  ('viewer', 'Read-only access')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
CROSS JOIN (VALUES
  ('clients:read'), ('clients:write'),
  ('calls:read'), ('calls:write'),
  ('bookings:read'), ('bookings:write'),
  ('crm:read'), ('crm:write'),
  ('analytics:read'),
  ('settings:read'), ('settings:write'),
  ('users:read'), ('users:write')
) AS p(permission)
WHERE r.name = 'super_admin'
ON CONFLICT (role_id, permission) DO NOTHING;

INSERT INTO permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
CROSS JOIN (VALUES
  ('clients:read'), ('clients:write'),
  ('calls:read'), ('calls:write'),
  ('bookings:read'), ('bookings:write'),
  ('crm:read'), ('crm:write'),
  ('analytics:read'),
  ('settings:read'), ('settings:write'),
  ('users:read')
) AS p(permission)
WHERE r.name = 'admin'
ON CONFLICT (role_id, permission) DO NOTHING;

INSERT INTO permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
CROSS JOIN (VALUES
  ('clients:read'),
  ('calls:read'),
  ('bookings:read'), ('bookings:write'),
  ('crm:read'),
  ('analytics:read')
) AS p(permission)
WHERE r.name = 'agent'
ON CONFLICT (role_id, permission) DO NOTHING;

INSERT INTO permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
CROSS JOIN (VALUES
  ('clients:read'),
  ('calls:read'),
  ('bookings:read'),
  ('analytics:read')
) AS p(permission)
WHERE r.name = 'viewer'
ON CONFLICT (role_id, permission) DO NOTHING;

-- ─────────────────────────────────────────────
-- 6. SEED: SUPER ADMIN USER (working login)
-- password_hash is a real bcrypt hash generated by pgcrypto and is verifiable
-- by bcryptjs (bcrypt.compare) in backend/src/dashboard-api/auth.route.ts.
--   email:    admin@gravvia.com
--   password: Admin1234!
-- >>> CHANGE THIS PASSWORD before production use. <<<
-- ─────────────────────────────────────────────
INSERT INTO users (email, name, password_hash, role, is_active)
VALUES (
  'admin@gravvia.com',
  'Gravvia Admin',
  crypt('Admin1234!', gen_salt('bf', 10)),
  'super_admin',
  true
)
ON CONFLICT (email) DO NOTHING;

-- ─────────────────────────────────────────────
-- 7. SEED: SAMPLE CLIENTS + SETTINGS + CONTACTS
-- ─────────────────────────────────────────────
INSERT INTO clients (id, name, slug, industry, timezone, phone_numbers, status, retell_agent_id) VALUES
  ('a1b2c3d4-0000-0000-0000-000000000001', 'Bright Smile Dental', 'bright-smile-dental', 'dental', 'America/New_York', ARRAY['+12125550100'], 'active', NULL),
  ('a1b2c3d4-0000-0000-0000-000000000002', 'Serenity Med Spa', 'serenity-med-spa', 'medical', 'America/Los_Angeles', ARRAY['+13105550200'], 'active', NULL),
  ('a1b2c3d4-0000-0000-0000-000000000003', 'Parker & Associates Law', 'parker-law', 'legal', 'America/Chicago', ARRAY['+13125550300'], 'active', NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO client_settings (
  client_id, agent_prompt, agent_personality, agent_tone,
  booking_enabled, booking_rules, notification_emails, crm_type
) VALUES
  (
    'a1b2c3d4-0000-0000-0000-000000000001',
    'You are a friendly receptionist for Bright Smile Dental. Help patients book appointments, answer FAQs about our services, and transfer to a live person when needed.',
    'warm', 'friendly', true,
    '{"advance_booking_hours":24,"max_advance_booking_days":60,"buffer_minutes":15,"working_hours":{"monday":{"open":"09:00","close":"17:00"},"tuesday":{"open":"09:00","close":"17:00"},"wednesday":{"open":"09:00","close":"17:00"},"thursday":{"open":"09:00","close":"17:00"},"friday":{"open":"09:00","close":"15:00"}},"blackout_dates":[],"lead_qualification_required":false,"lead_qualification_fields":[]}',
    ARRAY['team@brightsmiledental.com'], 'gohighlevel'
  ),
  (
    'a1b2c3d4-0000-0000-0000-000000000002',
    'You are a professional assistant for Serenity Med Spa. Help clients learn about our treatments and book consultations.',
    'professional', 'calm', true,
    '{"advance_booking_hours":48,"max_advance_booking_days":90,"buffer_minutes":30,"working_hours":{"tuesday":{"open":"10:00","close":"19:00"},"wednesday":{"open":"10:00","close":"19:00"},"thursday":{"open":"10:00","close":"19:00"},"friday":{"open":"10:00","close":"19:00"},"saturday":{"open":"10:00","close":"16:00"}},"blackout_dates":[],"lead_qualification_required":true,"lead_qualification_fields":["first_name","email"]}',
    ARRAY['info@serenityspa.com'], 'hubspot'
  ),
  (
    'a1b2c3d4-0000-0000-0000-000000000003',
    'You are a professional intake specialist for Parker & Associates. Always require a human attorney to speak with prospective clients before booking.',
    'formal', 'authoritative', false,
    '{"advance_booking_hours":0,"max_advance_booking_days":0,"buffer_minutes":0,"working_hours":{},"blackout_dates":[],"lead_qualification_required":true,"lead_qualification_fields":["case_type","urgency"]}',
    ARRAY['intake@parkerlaw.com', 'managing@parkerlaw.com'], 'salesforce'
  )
ON CONFLICT (client_id) DO NOTHING;

INSERT INTO contacts (client_id, first_name, last_name, phone, email, tags) VALUES
  ('a1b2c3d4-0000-0000-0000-000000000001', 'John', 'Smith', '+19175550101', 'john.smith@example.com', ARRAY['new-patient']),
  ('a1b2c3d4-0000-0000-0000-000000000002', 'Maria', 'Garcia', '+13235550202', 'maria@example.com', ARRAY['vip'])
ON CONFLICT DO NOTHING;

-- ============================================================================
-- DONE. Verify with:
--   SELECT email, role FROM users;
--   SELECT name, slug, crm_type IS NOT NULL FROM clients;
-- Then log in to the dashboard with admin@gravvia.com / Admin1234!
-- ============================================================================
