export { clientService, ClientService } from './client.service.js';
export { contactService, ContactService } from './contact.service.js';
export { callService, CallService } from './call.service.js';
export { userService, UserService } from './user.service.js';
export { ticketService, TicketService } from './ticket.service.js';
export { onboardingService, OnboardingService } from './onboarding.service.js';
export { actionItemService, ActionItemService } from './actionItem.service.js';
export { callRecordService, CallRecordService } from './callRecord.service.js';
export { provisioningService, ProvisioningService } from './provisioning.service.js';
export type { ProvisionOptions, ProvisionResult } from './provisioning.service.js';
export { writeAuditLog } from './audit.service.js';
export { knowledgeService, KnowledgeService } from './knowledge.service.js';
export type { ClientKnowledge, KnowledgeSearchResult } from './knowledge.service.js';
